[package]
name = "mmspellbook"
edition = "2021"
authors = ["CocytusDEDI"]
description = "MMSpellbook (Magic Modelling Spellbook) is a magic system for Godot that allows for the creation of custom spells"

[dependencies]

[profile.release]
lto = true
